import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//dynamic import Dictaphone
const Dictaphone = dynamic(() => import('../components/Dictaphone'), { ssr: false })
import { useSession, signIn, signOut } from "next-auth/react"
import { useEffect, useState } from 'react'
import { PencilIcon } from '@heroicons/react/solid'
import { EyeIcon } from '@heroicons/react/solid'

const Home: NextPage = () => {
  const [clipsMade, setClipsMade] = useState([]);
  const [activationPhrase, setActivationPhrase] = useState('Clip that');


  const { data: session } = useSession()
  return (
    <div className={'bg-gray-800 text-white min-h-screen flex-row'}>

      <Head>
        <title>Make Twitch clips with your voice!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-72 min-h-screen shadow-md bg-gray-600 px-1 float-left overflow-y-auto ">
        <ul className="relative">
          <li key={'clipbot.tv'} className="relative">
            <a href='https://clipbot.tv?utm_source=clipthat' target='_blank' rel='noreferrer noopener'>
            <div  className='text-lg flex-col text-center py-4 px-6 w-full text-blue-300 text-ellipsis bg-gray-800 hover:text-gray-900 hover:bg-gray-400 mt-2 p-2 transition duration-300 ease-in-out' >
            <Image alt='Clipbot.tv logo' className='m-auto mb-1' height='45px' width='128px' src='/clipbot-logo.png' /><p className='w-full'>Want to automatically post your clips to Tiktok and Youtube? </p>
            </div>
            </a>
          </li>
          {clipsMade.slice().reverse().map(({ url, name, src }, index) => (<li key={url} className="relative h-42">
            <div className='flex justify-between items-center text-lg py-4 px-6 h-12 overflow-hidden text-blue-300 text-ellipsis whitespace-nowrap rounded bg-gray-800 hover:text-gray-900 hover:bg-gray-400 mt-2 p-2 transition duration-300 ease-in-out' >
              {name}
              <a target='_blank' href={url} rel='noreferrer noopener' className=''><PencilIcon className='ml-4 w-8 h-8 p-1 border-gray-300 border-2 rounded-md hover:bg-slate-50' /></a>
              <a target='_blank' href={(url as string).replace('/edit', '')} rel='noreferrer noopener' className=''><EyeIcon className='ml-4 w-8 h-8 p-1 border-gray-300 border-2 rounded-md hover:bg-slate-50' /></a>
            </div>
            <video className='w-full h-full' src={src} controls />
          </li>))}
        </ul>
      </div>

      <div
        className="p-12 text-center relative overflow-hidden h-screen bg-no-repeat bg-cover rounded-lg"
      >
        <div
          className="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed"
          style={{ backgroundColor: "rgba(0, 0, 0, 0.6)" }}
        >
          <div className="flex justify-center items-center h-full">
            <div className="text-white">
              <h2 className="font-semibold text-4xl mb-4 uppercase" >{activationPhrase}!</h2>
              <h4 className="font-semibold text-xl mb-1">Just say &ldquo;{activationPhrase}&rdquo; to make a live clip on Twitch.<br /> Clips will show up on the bar on the left.</h4>
              <h6 className="font-semibold text-sm mb-6 italic">(Supported only on Chrome)</h6>
              <div
                className={"inline-block px-7 py-3 mb-1 border-2 border-gray-200 text-gray-200 font-medium text-sm leading-snug uppercase rounded focus:outline-none focus:ring-0 transition duration-150 ease-in-out" + (session ? "" : " hover:bg-gray-800 cursor-pointer")}
                onClick={() => {session ? null : signIn('twitch')}}
                data-mdb-ripple="true"
                data-mdb-ripple-color="light"
                
              >
                {session ? (
                  <>
                    Your Channel: <span className='text-blue-200'>{session?.user?.name}</span> <br />
                    <Dictaphone setClipsMade={setClipsMade} clipsMade={clipsMade} activationPhrase={activationPhrase} setActivationPhrase={setActivationPhrase} />
                    {/* <button onClick={() => signOut()}>Sign out</button> */}
                  </>
                ) :
                  (
                    <>
                      <div className='flex text-xl'><Image src='/twitch-logo.png' width='28px' height='24px' /><p className={'ml-2'}>Sign in to Twitch</p></div>
                    </>
                  )}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
